import {useState,useRef,useLayoutEffect} from 'react';
import {Plus,Smile,ArrowUp,X,FileText,LoaderCircle} from 'lucide-react';
import {IconButton,Dropdown} from './UI';
export default function MessageInput({onSend,busy,onNotice,focusKey}){
 const [value,setValue]=useState(''),[emoji,setEmoji]=useState(false),[files,setFiles]=useState([]);
 const textarea=useRef(null),fileInput=useRef(null);
 useLayoutEffect(()=>{textarea.current.style.height='auto';textarea.current.style.height=`${Math.min(textarea.current.scrollHeight,160)}px`;},[value]);
 useLayoutEffect(()=>{setValue('');setFiles([]);setEmoji(false);},[focusKey]);
 const submit=e=>{e?.preventDefault();if(!value.trim()||busy)return;const attachments=files.length?`\n\n[Local attachment names: ${files.map(f=>f.name).join(', ')}. Contents are not analyzed in this demo.]`:'';if(onSend(value+attachments)){setValue('');setFiles([]);textarea.current.focus();}};
 return <div className="composer-wrap"><form className={`composer ${busy?'is-busy':''}`} onSubmit={submit}>{files.length>0&&<div className="attachment-list">{files.map((f,i)=><span key={`${f.name}-${i}`}><FileText size={13}/>{f.name}<IconButton label={`Remove ${f.name}`} onClick={()=>setFiles(fs=>fs.filter((_,idx)=>idx!==i))}><X size={12}/></IconButton></span>)}</div>}<textarea ref={textarea} aria-label="Message Nexa AI" placeholder="Message Nexa AI..." value={value} maxLength={20000} rows={1} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit();}}}/><div className="composer-toolbar"><div className="composer-tools"><IconButton label="Attach files locally" disabled={busy} onClick={()=>fileInput.current.click()}><Plus size={20}/></IconButton><input ref={fileInput} type="file" multiple hidden onChange={e=>{const incoming=[...e.target.files];setFiles(fs=>[...fs,...incoming].slice(0,5));e.target.value='';onNotice('Attachments stay local. This demo records names only, without analyzing file contents.');}}/><div className="menu-anchor"><IconButton label="Choose emoji" onClick={()=>setEmoji(!emoji)}><Smile size={19}/></IconButton>{emoji&&<Dropdown className="emoji-menu" onClose={()=>setEmoji(false)}>{['👋','💡','✨','😊','👍','🚀','🎯','❤️'].map(icon=><button key={icon} aria-label={`Insert ${icon}`} onClick={()=>{setValue(v=>v+icon);setEmoji(false);textarea.current.focus();}}>{icon}</button>)}</Dropdown>}</div><span className="composer-tool-divider"/><span className="composer-model"><span className="status-dot"/>Nexa · Local demo</span></div><div className="send-tools"><span className="enter-hint">Enter to send</span><button className="send-button" type="submit" disabled={!value.trim()||busy} aria-label={busy?'Generating response':'Send message'}>{busy?<LoaderCircle size={19} className="spin"/>:<ArrowUp size={20}/>}</button></div></div></form><div className="composer-footer"><span>Nexa uses simulated replies. Your conversations stay in this browser.</span><span className="keyboard-hint">Shift + Enter for a new line</span></div></div>;
}
